// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: check.proto

package com.wql.locks.grpcpool2;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   */
  String getService();
  /**
   * <code>string service = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();
}
