// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: check.proto

package com.wql.locks.grpcpool2;

public final class HealthCheckService {
  private HealthCheckService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013check.proto\022\004grpc\"%\n\022HealthCheckReques" +
      "t\022\017\n\007service\030\001 \001(\t\"\212\001\n\023HealthCheckRespon" +
      "se\0227\n\006status\030\001 \001(\0162\'.grpc.HealthCheckRes" +
      "ponse.ServingStatus\":\n\rServingStatus\022\013\n\007" +
      "UNKNOWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013NOT_SERVING\020\0022" +
      "F\n\006Health\022<\n\005Check\022\030.grpc.HealthCheckReq" +
      "uest\032\031.grpc.HealthCheckResponseB.\n\016grpc." +
      "health.v1B\022HealthCheckServiceP\001\242\002\005HAOKEb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_HealthCheckRequest_descriptor,
        new String[] { "Service", });
    internal_static_grpc_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_HealthCheckResponse_descriptor,
        new String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
