// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: check.proto

package com.wql.locks.grpcpool2;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.HealthCheckResponse.ServingStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.grpc.HealthCheckResponse.ServingStatus status = 1;</code>
   */
  com.wql.locks.grpcpool2.HealthCheckResponse.ServingStatus getStatus();
}
